import {describe,it,expect,afterEach} from 'vitest';
import {createPluginRuntimeTestHost,type PluginRuntimeTestHost} from '@emdash-cms/plugin-test';
import {validateBlockResponse} from '@emdash-cms/blocks/server';
import {createEventsCollectionBlueprint,createVenuesCollectionBlueprint,createOrganizersCollectionBlueprint} from '../src/schema/blueprint';
import {saveCollectionBindings,collectionBindings} from '../src/domain/collections';
import type {EventualContext} from '../src/storage';

let h:PluginRuntimeTestHost|undefined;
afterEach(async()=>{await h?.dispose();h=undefined;});
const bindings={events:'activities',venues:'locations',organizers:'hosts'};
async function setup(){
 h=await createPluginRuntimeTestHost({site:{url:'https://audit.example.com',locale:'fr'},i18n:{defaultLocale:'fr',locales:['fr','en']}});
 await h.fixtures.collection(createEventsCollectionBlueprint({eventCollection:'activities',venueCollection:'locations',organizerCollection:'hosts',legacyCompatibility:true}) as any);
 await h.fixtures.collection({...createVenuesCollectionBlueprint({legacyCompatibility:true}),slug:'locations'} as any);
 await h.fixtures.collection({...createOrganizersCollectionBlueprint(),slug:'hosts'} as any);
 return h;
}
describe('Configurable native collections',{timeout:60_000},()=>{
 it('validates schema and reference targets before changing stored selections',async()=>{
   const schema=createEventsCollectionBlueprint({eventCollection:'activities',venueCollection:'locations',organizerCollection:'hosts'});
   let saved:any;
   const ctx={schema:{listCollections:async()=>[schema,{...createVenuesCollectionBlueprint(),slug:'locations'},{...createOrganizersCollectionBlueprint(),slug:'hosts'}]},settings:{set:async(_key:string,value:unknown)=>{saved=value;},get:async()=>saved}} as unknown as EventualContext;
   await saveCollectionBindings(ctx,bindings);expect(saved).toEqual(bindings);
   await expect(saveCollectionBindings(ctx,{...bindings,venues:'hosts'})).rejects.toThrow('reference target');
   expect(saved).toEqual(bindings);
   schema.fields.find(item=>item.slug==='description')!.type='string';
   await expect(saveCollectionBindings(ctx,bindings)).rejects.toThrow('portableText');
   schema.fields.find(item=>item.slug==='description')!.type='portableText';
   schema.fields.find(item=>item.slug==='timezone')!.translatable=true;
   await expect(saveCollectionBindings(ctx,bindings)).rejects.toThrow('translatable');
 });
 it('connects settings, feeds, MCP and the native panel to nonstandard collections',async()=>{
  const host=await setup();
  const admin=await host.fixtures.user({email:'bindings-admin@example.com',role:'admin',emailVerified:true});
  const page=await host.admin.loadPage('/settings',{user:admin});expect(validateBlockResponse(page,{}).valid).toBe(true);
  const saved=await host.admin.submit('/settings','save-settings',bindings,{user:admin,blockId:'collection-settings'});
  expect(JSON.stringify(saved)).not.toContain('Settings not saved');
  expect((await host.transport.invokeRoute('mcp/settings/get',{})) as any).toMatchObject({collections:bindings});
  await host.fixtures.content('locations',{id:'hall',status:'published',locale:'fr',data:{name:'Salle',street:'Rue des voisins'}});
  await host.fixtures.content('hosts',{id:'host',status:'published',locale:'fr',data:{name:'Association'}});
  await host.fixtures.content('activities',{id:'event',status:'published',locale:'fr',data:{title:'Rencontre',start:'2026-11-15T10:00:00Z',end:'2026-11-15T11:00:00Z',timezone:'UTC',all_day:false,venue:'hall',organizer_ref:'host'}});
  const json:any=await host.transport.invokeRoute('publicEvents',{from:'2026-11-01',through:'2026-11-30'});
  expect(json.events[0]).toMatchObject({title:'Rencontre',venue:{name:'Salle'},organizer:'Association'});
  expect(JSON.stringify(await host.transport.invokeRoute('mcp/events/list',{}))).toContain('Rencontre');
  expect(JSON.stringify(await host.transport.invokeRoute('mcp/venues/list',{}))).toContain('Salle');
  expect(JSON.stringify(await host.transport.invokeRoute('mcp/organizers/list',{}))).toContain('Association');
  const panel=await host.admin.loadEditorPanel('event-schedule','activities','event',{user:admin});
  const validation=validateBlockResponse(panel,{});expect(validation.valid,JSON.stringify(validation)).toBe(true);
  expect(JSON.stringify(panel)).toContain('Rue des voisins');
  expect((await host.actions.content.update('activities','event',{data:{timezone:'Mars/Olympus'}})).success).toBe(false);
  expect((await host.actions.content.delete('locations','hall')).success).toBe(false);
  const workspace=await host.admin.loadPage('/events',{user:admin});
  expect(validateBlockResponse(workspace,{}).valid).toBe(true);
  expect(JSON.stringify(workspace)).toContain('/content/activities/');
  const editor=await host.fixtures.user({email:'bindings-editor@example.com',role:'editor',emailVerified:true});
  await host.admin.submit('/settings','save-settings',{events:'events',venues:'venues',organizers:'organizers',defaultTimezone:'UTC'},{user:editor,blockId:'collection-settings'});
  expect((await host.transport.invokeRoute('mcp/settings/get',{})) as any).toMatchObject({collections:bindings});
  const legacy={id:'old',title:'Legacy custom migration',description:'**Preserved**',start:'2026-11-16',end:'2026-11-16',allDay:true,timezone:'Europe/Paris',location:'',organizer:'',externalUrl:'',imageUrl:'',categories:[],published:false,exceptions:[],createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};
  await host.fixtures.plugin.storage('events','old',legacy);
  const preview:any=await host.transport.invokeRoute('mcp/transfer/migrateToNative',{dryRun:true});
  expect(preview.ok,JSON.stringify(preview)).toBe(true);expect(preview.venueCollection).toBe('locations');
  expect(await host.inspect.content.list('activities')).toHaveLength(1);
  const migrated:any=await host.transport.invokeRoute('mcp/transfer/migrateToNative',{});
  expect(migrated.ok,JSON.stringify(migrated)).toBe(true);
  const entry=await host.inspect.content.get('activities',migrated.events[0].nativeId);
  expect(entry?.data.legacy_id).toBe('old');expect(entry?.data.description).toEqual(expect.any(Array));
  expect(await host.inspect.storage.get('events','old')).toEqual(legacy);
  const rerun:any=await host.transport.invokeRoute('mcp/transfer/migrateToNative',{});
  expect(rerun.events[0].status).toBe('already_exists');
 });
 it('keeps a clean schema working when saving venues and rescheduling published events',async()=>{
  h=await createPluginRuntimeTestHost({site:{url:'https://audit.example.com',locale:'fr'}});
  await h.fixtures.collection(createEventsCollectionBlueprint() as any);
  await h.fixtures.collection(createVenuesCollectionBlueprint() as any);
  await h.fixtures.collection(createOrganizersCollectionBlueprint() as any);
  const admin=await h.fixtures.user({email:'clean-admin@example.com',role:'admin',emailVerified:true});
  await h.fixtures.content('venues',{id:'hall',status:'published',data:{name:'Hall'}});
  await h.fixtures.content('events',{id:'clean',slug:'clean',status:'published',data:{title:'Clean event',description:[{_type:'block',children:[{_type:'span',text:'Rich announcement',marks:['strong']}]}],start:'2026-11-15T10:00:00Z',end:'2026-11-15T11:00:00Z',all_day:false,timezone:'UTC',categories:'Music, Community'}});
  const panel:any=await h.admin.loadEditorPanel('event-schedule','events','clean',{user:admin});
  expect(JSON.stringify(panel)).not.toContain('"action_id":"categories"');
  const forms:any[]=[];const walk=(blocks:any[])=>{for(const block of blocks){if(block.type==='form')forms.push(block);if(block.blocks)walk(block.blocks);}};walk(panel.blocks);
  const form=forms.find(form=>form.submit.action_id.startsWith('apply-details'));
  const saved:any=await h.admin.submitEditorPanel('event-schedule','events','clean',form.submit.action_id,{venue:'hall',organizer_ref:''},{user:admin,blockId:form.block_id});
  expect(saved.toast?.type,JSON.stringify(saved)).toBe('success');
  const publication=await h.actions.content.publish('events','clean');
  expect(publication.success,JSON.stringify(publication)).toBe(true);
  const revision:any=await h.inspect.content.get('events','clean');
  expect(revision.data.categories).toBe('Music, Community');
  expect(revision.data.description[0].children[0].marks).toEqual(['strong']);
  const changed=await h.actions.content.update('events','clean',{data:{start:'2026-11-16T10:00:00Z',end:'2026-11-16T11:00:00Z'}});
  expect(changed.success,JSON.stringify(changed)).toBe(true);
  expect((await h.actions.content.publish('events','clean')).success).toBe(true);
  const draft:any=await h.inspect.content.get('events','clean');
  expect(draft.data.event_status).toBe('rescheduled');
  expect(draft.data).not.toHaveProperty('schedule_history');
  expect(draft.data).not.toHaveProperty('previous_start_date');
 });
 it('fails closed when a configured collection disappears without disrupting unrelated content',async()=>{
  const host=await setup();await host.fixtures.plugin.setting('collections',{...bindings,events:'missing'});
  await host.fixtures.collection({slug:'notes',label:'Notes',fields:[{slug:'title',label:'Title',type:'string',translatable:true}]} as any);
  expect((await host.actions.content.create('notes',{data:{title:'Unaffected'}})).success).toBe(true);
  const response=await host.actions.routes.request('calendar',{method:'GET',url:'https://audit.example.com/_emdash/api/plugins/eventual/calendar'});
  expect(response.status).toBe(503);
  expect(await host.inspect.storage.list('events')).toHaveLength(0);
  const ctx={settings:{get:async()=>bindings},schema:{listCollections:async()=>[]}} as unknown as EventualContext;
  await expect(collectionBindings(ctx)).rejects.toThrow('selected event collection is missing');
 });
});
